### ISSUE TITLE
Application.run() logs every request and event

### ISSUE THREAD

**Issue by onebytegone** [silvermine/lambda-express#1]
When using [`Application`'s `run()` function](https://github.com/silvermine/lambda-express/blob/39fc7fa5595d5179082be06ef601e71138cbc5e6/src/Application.ts#L78-L84), the entire `RequestEvent`, `HandlerContext`, and response are logged. While logging that information can be helpful at times, this seems like debug code. Should [the `console.log`](https://github.com/silvermine/lambda-express/blob/39fc7fa5595d5179082be06ef601e71138cbc5e6/src/Application.ts#L82) be removed or at least be allowed to be disabled?

**Comment by jthomerson** [comment]
That code isn't implemented yet.

**Comment by jthomerson** [comment]
It's literally just a stub for the API of the class.

**Comment by onebytegone** [comment]
Ok, cool. That makes sense. Thanks @jthomerson.
