### ISSUE TITLE
Support Promises in Middleware / Handlers

### ISSUE THREAD

**Issue by jthomerson** [silvermine/lambda-express#30]
Since our org typically prefers promises over callbacks, I was excited to see that 5.x versions of Express will support promises. Please evaluate what they support and whether we can support it while still supporting the callback variant as well.

*References:*
 * https://github.com/expressjs/express/issues/2259#issuecomment-433586394
 * https://github.com/pillarjs/router/tree/v2.0.0-alpha.1#middleware
 * https://github.com/pillarjs/router/commit/d2bce0c09d424ea89e77cef7743e12f411ed94f7
 * https://github.com/expressjs/express/pull/2237

**Comment by jthomerson** [comment]
Assigned to @yokuze and @onebytegone. You guys can work out who has better availability to look into this.

**Comment by onebytegone** [comment]
Closed by #32
