### ISSUE TITLE
Consider escaping newline/paragraph separators in JSONP responses

### ISSUE THREAD

**Issue by onebytegone** [silvermine/lambda-express#36]
To fix https://github.com/expressjs/express/issues/1132, express started escaping [`\u2028`](https://www.fileformat.info/info/unicode/char/2028/index.htm) and [`\u2029`](https://www.fileformat.info/info/unicode/char/2029/index.htm) as these were valid in JSON, but not JS (was changed in [this proposal](https://github.com/tc39/proposal-json-superset)). Should lambda-express also perform a similar escaping?

See also: 
* http://timelessrepo.com/json-isnt-a-javascript-subset
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#JavaScript_and_JSON_differences

**Comment by jthomerson** [comment]
Makes sense to me. Good catch.

**Comment by onebytegone** [comment]
Closed with #42.
