### ISSUE TITLE
Consider returning "nosniff" for JSONP responses

### ISSUE THREAD

**Issue by onebytegone** [silvermine/lambda-express#38]
As part of preventing [Rosetta Flash](https://miki.it/blog/2014/7/8/abusing-jsonp-with-rosetta-flash/), express [sets the `X-Content-Type-Options` header to `nosniff`](https://github.com/expressjs/express/commit/f684a64df71a08c0caf2371aa305411df690a10f). lambda-express already has the `/**/` mitigation, however should `nosniff` also be added?

See also: https://helmetjs.github.io/docs/dont-sniff-mimetype/

**Comment by jthomerson** [comment]
Good find. Yes, let's add the same type of header-setting logic as Express. Also, let's add some comments in the code that clearly indicate that a) the nosniff header, b) the JS comment, and c) the typeof check are all mitigations against Rosetta Flash. Comment should reference this ticket.

**Comment by onebytegone** [comment]
Closed with #42.
